export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqZXlxdWlzc29uQGVtYWlsLmNvbS5iciIsImlhdCI6MTcxMDM1MjIzNiwiZXhwIjoxNzEwOTU3MDM2LCJhdWQiOiJzdHJpbmciLCJpc3MiOiJsb2dpbiIsInN1YiI6IjMifQ.zYZt5TQy7jaBIno2pyezETe1BnwzzvDu_0xt7_u1BV0';
